const { calculateSchema } = require("../src/calculate");

describe("CalcSchema", () => {
  test("Schema", () => {
    const data = calculateSchema(
      {
        0: {
          General: {
            Code: "21STCENMGM",
            Type: "Common Stock",
            Name: "21st Century Management Services Limited",
            Exchange: "NSE",
            CurrencyCode: "INR",
            CurrencyName: "Indian Rupee",
            CurrencySymbol: "INR",
            CountryName: "India",
            CountryISO: "IN",
            ISIN: "INE253B01015",
            Sector: "Financial Services",
            Industry: "Capital Markets",
            Description:
              "Twentyfirst Century Management Services Limited invests in capital and debt instruments in India. It invests and trades in shares and derivatives in the capital, and futures and options markets. The company was incorporated in 1986 and is based in Mumbai, India. Address: 2B, Grease House, Mumbai, India, 400015",
            FullTimeEmployees: 10,
            UpdatedAt: "2022-02-19",
          },
          Highlights: {
            MarketCapitalization: 358019744,
            MarketCapitalizationMln: 358.0197,
            EBITDA: 243228496,
            PERatio: 1.47,
            PEGRatio: null,
            WallStreetTargetPrice: null,
            BookValue: 60.19,
            DividendShare: 0,
            DividendYield: 0,
            EarningsShare: 23.095,
            EPSEstimateCurrentYear: 0,
            EPSEstimateNextYear: 0,
            EPSEstimateNextQuarter: 0,
            MostRecentQuarter: "2021-12-31",
            ProfitMargin: 0.0899,
            OperatingMarginTTM: 0.0898,
            ReturnOnAssetsTTM: 0.5734,
            ReturnOnEquityTTM: 0.1167,
            RevenueTTM: 2699094016,
            RevenuePerShareTTM: 256.947,
            QuarterlyRevenueGrowthYOY: 242.549,
            GrossProfitTTM: 72556000,
            DilutedEpsTTM: 23.095,
            QuarterlyEarningsGrowthYOY: 0,
          },
          Valuation: {
            TrailingPE: 1.47,
            ForwardPE: 0,
            PriceSalesTTM: 0.1326,
            PriceBookMRQ: 0.6215,
            EnterpriseValueRevenue: 0.1431,
            EnterpriseValueEbitda: 1.5866,
          },
          Technicals: {
            Beta: 0.4304,
            "52WeekHigh": 64,
            "52WeekLow": 11.6,
            "50DayMA": 45.199,
            "200DayMA": 37.519,
            SharesShort: 0,
            SharesShortPriorMonth: 0,
            ShortRatio: 0,
            ShortPercent: 0,
          },
          SplitsDividends: {
            ForwardAnnualDividendRate: 0,
            ForwardAnnualDividendYield: 0,
            PayoutRatio: 0,
            DividendDate: "0000-00-00",
            ExDividendDate: "2018-07-04",
            LastSplitFactor: "",
            LastSplitDate: "0000-00-00",
          },
          Earnings: {
            Last_0: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_1: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_2: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_3: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
          },
          Financials: {},
        },
        1: {
          General: {
            Code: "3IINFOLTD",
            Type: "Common Stock",
            Name: "3i Infotech Limited",
            Exchange: "NSE",
            CurrencyCode: "INR",
            CurrencyName: "Indian Rupee",
            CurrencySymbol: "INR",
            CountryName: "India",
            CountryISO: "IN",
            ISIN: "INE748C01038",
            Sector: "Technology",
            Industry: "Information Technology Services",
            Description:
              "3i Infotech Limited provides IP based software solutions and information technology services in India, North America, the Asia Pacific, the Middle East, Africa, the Kingdom of Saudi Arabia, and South Asia. The company offers NuRe Edge that provides consolidated secure access services in one single platform; NuRe desk, a next-generation virtual desktop solution that has a virtualization engine; NuRe 3i that designs, constructs, and manages full-stack cloud solutions including , maintain crucial operational applications supporting the entire Eco-system in the cloud; and NuRe 3i+, an enterprise-grade cloud converged infrastructure that allows customers to consolidate business critical middleware and application workloads on the Oracle OCI or at the edge. It also provides MAGGIET, an integrated intelligent process automation solution; Flexib, a unique digital testing platform to accelerate QAOps for functional and Non-functional test automations in a DevOps and non-DevOps environments; Momenta, a solution with integrated AI and data science analytics platform; 3iAires Suite that digitizes enterprise's core processes to orchestrate a robust brand experience across all engagement channels; and Universo, a scheme management solution with modular and configurable options, which is developed on Open Source technologies to enable quick automation of the scheme management process right from beneficiary management to benefit disbursement and reconciliation through various intermediate processes. The company serves customers in banking, insurance, capital markets, asset and wealth management, government, manufacturing, retail, distribution, telecom, and healthcare industry verticals. 3i Infotech Limited was incorporated in 1993 and is headquartered in Navi Mumbai, India. Address: Tower # 5, Navi Mumbai, India, 400 703",
            FullTimeEmployees: 4000,
            UpdatedAt: "2022-02-19",
          },
          Highlights: {
            MarketCapitalization: 10438404096,
            MarketCapitalizationMln: 10438.4041,
            EBITDA: null,
            PERatio: 17.7521,
            PEGRatio: null,
            WallStreetTargetPrice: null,
            BookValue: 44.223,
            DividendShare: 0,
            DividendYield: 0,
            EarningsShare: 3.501,
            EPSEstimateCurrentYear: 0,
            EPSEstimateNextYear: 0,
            EPSEstimateNextQuarter: 0,
            MostRecentQuarter: "2021-12-31",
            ProfitMargin: 0.4456,
            OperatingMarginTTM: -0.1577,
            ReturnOnAssetsTTM: -0.0289,
            ReturnOnEquityTTM: 0.4508,
            RevenueTTM: 6505500160,
            RevenuePerShareTTM: 39.384,
            QuarterlyRevenueGrowthYOY: -0.398,
            GrossProfitTTM: 551700000,
            DilutedEpsTTM: 3.501,
            QuarterlyEarningsGrowthYOY: 0,
          },
          Valuation: {
            TrailingPE: 17.7521,
            ForwardPE: 0,
            PriceSalesTTM: 1.6046,
            PriceBookMRQ: 1.5649,
            EnterpriseValueRevenue: 0.8975,
            EnterpriseValueEbitda: 1.9433,
          },
          Technicals: {
            Beta: 1.1755,
            "52WeekHigh": 119.3,
            "52WeekLow": 6,
            "50DayMA": 85.354,
            "200DayMA": 85.557,
            SharesShort: 0,
            SharesShortPriorMonth: 0,
            ShortRatio: 0,
            ShortPercent: 0,
          },
          SplitsDividends: {
            ForwardAnnualDividendRate: 0,
            ForwardAnnualDividendYield: 0,
            PayoutRatio: 0,
            DividendDate: "0000-00-00",
            ExDividendDate: "2011-07-07",
            LastSplitFactor: "1:10",
            LastSplitDate: "2021-08-30",
          },
          Earnings: {
            Last_0: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_1: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_2: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
            Last_3: {
              date: "0000-00-00",
              epsActual: 0,
              epsEstimate: 0,
              epsDifference: 0,
              surprisePercent: 0,
            },
          },
          Financials: {},
        },
      },
      {},
      "NSE",
      "Insfun"
    );
    console.log(data);
    expect(data).toEqual([
      [
        {
          PutRequest: {
            Item: {
              exchg: "NSE",
              id: "21STCENMGM",
              isin: "INE253B01015",
              __typename: "Insfun",
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              ana: {
                General: {
                  Code: "21STCENMGM",
                  Type: "Common Stock",
                  Name: "21st Century Management Services Limited",
                  Exchange: "NSE",
                  CurrencyCode: "INR",
                  CurrencyName: "Indian Rupee",
                  CurrencySymbol: "INR",
                  CountryName: "India",
                  CountryISO: "IN",
                  ISIN: "INE253B01015",
                  Sector: "Financial Services",
                  Industry: "Capital Markets",
                  Description:
                    "Twentyfirst Century Management Services Limited invests in capital and debt instruments in India. It invests and trades in shares and derivatives in the capital, and futures and options markets. The company was incorporated in 1986 and is based in Mumbai, India. Address: 2B, Grease House, Mumbai, India, 400015",
                  FullTimeEmployees: 10,
                  UpdatedAt: "2022-02-19",
                },
                Highlights: {
                  MarketCapitalization: 358019744,
                  MarketCapitalizationMln: 358.0197,
                  EBITDA: 243228496,
                  PERatio: 1.47,
                  PEGRatio: null,
                  WallStreetTargetPrice: null,
                  BookValue: 60.19,
                  DividendShare: 0,
                  DividendYield: 0,
                  EarningsShare: 23.095,
                  EPSEstimateCurrentYear: 0,
                  EPSEstimateNextYear: 0,
                  EPSEstimateNextQuarter: 0,
                  MostRecentQuarter: "2021-12-31",
                  ProfitMargin: 0.0899,
                  OperatingMarginTTM: 0.0898,
                  ReturnOnAssetsTTM: 0.5734,
                  ReturnOnEquityTTM: 0.1167,
                  RevenueTTM: 2699094016,
                  RevenuePerShareTTM: 256.947,
                  QuarterlyRevenueGrowthYOY: 242.549,
                  GrossProfitTTM: 72556000,
                  DilutedEpsTTM: 23.095,
                  QuarterlyEarningsGrowthYOY: 0,
                },
                Valuation: {
                  TrailingPE: 1.47,
                  ForwardPE: 0,
                  PriceSalesTTM: 0.1326,
                  PriceBookMRQ: 0.6215,
                  EnterpriseValueRevenue: 0.1431,
                  EnterpriseValueEbitda: 1.5866,
                },
                Technicals: {
                  Beta: 0.4304,
                  "52WeekHigh": 64,
                  "52WeekLow": 11.6,
                  "50DayMA": 45.199,
                  "200DayMA": 37.519,
                  SharesShort: 0,
                  SharesShortPriorMonth: 0,
                  ShortRatio: 0,
                  ShortPercent: 0,
                },
                SplitsDividends: {
                  ForwardAnnualDividendRate: 0,
                  ForwardAnnualDividendYield: 0,
                  PayoutRatio: 0,
                  DividendDate: "0000-00-00",
                  ExDividendDate: "2018-07-04",
                  LastSplitFactor: "",
                  LastSplitDate: "0000-00-00",
                },
                Earnings: {
                  Last_0: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_1: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_2: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_3: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                },
                Financials: {},
              },
            },
          },
        },
        {
          PutRequest: {
            Item: {
              exchg: "NSE",
              id: "3IINFOLTD",
              isin: "INE748C01038",
              __typename: "Insfun",
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              ana: {
                General: {
                  Code: "3IINFOLTD",
                  Type: "Common Stock",
                  Name: "3i Infotech Limited",
                  Exchange: "NSE",
                  CurrencyCode: "INR",
                  CurrencyName: "Indian Rupee",
                  CurrencySymbol: "INR",
                  CountryName: "India",
                  CountryISO: "IN",
                  ISIN: "INE748C01038",
                  Sector: "Technology",
                  Industry: "Information Technology Services",
                  Description:
                    "3i Infotech Limited provides IP based software solutions and information technology services in India, North America, the Asia Pacific, the Middle East, Africa, the Kingdom of Saudi Arabia, and South Asia. The company offers NuRe Edge that provides consolidated secure access services in one single platform; NuRe desk, a next-generation virtual desktop solution that has a virtualization engine; NuRe 3i that designs, constructs, and manages full-stack cloud solutions including , maintain crucial operational applications supporting the entire Eco-system in the cloud; and NuRe 3i+, an enterprise-grade cloud converged infrastructure that allows customers to consolidate business critical middleware and application workloads on the Oracle OCI or at the edge. It also provides MAGGIET, an integrated intelligent process automation solution; Flexib, a unique digital testing platform to accelerate QAOps for functional and Non-functional test automations in a DevOps and non-DevOps environments; Momenta, a solution with integrated AI and data science analytics platform; 3iAires Suite that digitizes enterprise's core processes to orchestrate a robust brand experience across all engagement channels; and Universo, a scheme management solution with modular and configurable options, which is developed on Open Source technologies to enable quick automation of the scheme management process right from beneficiary management to benefit disbursement and reconciliation through various intermediate processes. The company serves customers in banking, insurance, capital markets, asset and wealth management, government, manufacturing, retail, distribution, telecom, and healthcare industry verticals. 3i Infotech Limited was incorporated in 1993 and is headquartered in Navi Mumbai, India. Address: Tower # 5, Navi Mumbai, India, 400 703",
                  FullTimeEmployees: 4000,
                  UpdatedAt: "2022-02-19",
                },
                Highlights: {
                  MarketCapitalization: 10438404096,
                  MarketCapitalizationMln: 10438.4041,
                  EBITDA: null,
                  PERatio: 17.7521,
                  PEGRatio: null,
                  WallStreetTargetPrice: null,
                  BookValue: 44.223,
                  DividendShare: 0,
                  DividendYield: 0,
                  EarningsShare: 3.501,
                  EPSEstimateCurrentYear: 0,
                  EPSEstimateNextYear: 0,
                  EPSEstimateNextQuarter: 0,
                  MostRecentQuarter: "2021-12-31",
                  ProfitMargin: 0.4456,
                  OperatingMarginTTM: -0.1577,
                  ReturnOnAssetsTTM: -0.0289,
                  ReturnOnEquityTTM: 0.4508,
                  RevenueTTM: 6505500160,
                  RevenuePerShareTTM: 39.384,
                  QuarterlyRevenueGrowthYOY: -0.398,
                  GrossProfitTTM: 551700000,
                  DilutedEpsTTM: 3.501,
                  QuarterlyEarningsGrowthYOY: 0,
                },
                Valuation: {
                  TrailingPE: 17.7521,
                  ForwardPE: 0,
                  PriceSalesTTM: 1.6046,
                  PriceBookMRQ: 1.5649,
                  EnterpriseValueRevenue: 0.8975,
                  EnterpriseValueEbitda: 1.9433,
                },
                Technicals: {
                  Beta: 1.1755,
                  "52WeekHigh": 119.3,
                  "52WeekLow": 6,
                  "50DayMA": 85.354,
                  "200DayMA": 85.557,
                  SharesShort: 0,
                  SharesShortPriorMonth: 0,
                  ShortRatio: 0,
                  ShortPercent: 0,
                },
                SplitsDividends: {
                  ForwardAnnualDividendRate: 0,
                  ForwardAnnualDividendYield: 0,
                  PayoutRatio: 0,
                  DividendDate: "0000-00-00",
                  ExDividendDate: "2011-07-07",
                  LastSplitFactor: "1:10",
                  LastSplitDate: "2021-08-30",
                },
                Earnings: {
                  Last_0: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_1: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_2: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                  Last_3: {
                    date: "0000-00-00",
                    epsActual: 0,
                    epsEstimate: 0,
                    epsDifference: 0,
                    surprisePercent: 0,
                  },
                },
                Financials: {},
              },
            },
          },
        },
      ],
    ]);
  });
});
