/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7d526af8-e47d-4096-a54f-b16374b43418",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3N0D6fw9V",
    "aws_user_pools_web_client_id": "5lnl445333npfc9tj5rlcrd9vo",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_appsync_graphqlEndpoint": "https://j6qsr3lbtvchnl6yhykwelxj2m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "goal-images115157-usdev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_usdev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
