/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:850b7611-90f6-45d0-87a5-68cc62a4fee3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SBAUMngHM",
    "aws_user_pools_web_client_id": "63g2smsml7egik1h7a3pb08jr2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_appsync_graphqlEndpoint": "https://2x5orxpn4vgtdmtheb3q6h5tuu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "goal-images104733-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ]
};


export default awsmobile;
