/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:082d9d3f-a45b-480d-af35-64aeafd1bd9c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BBncFECx0",
    "aws_user_pools_web_client_id": "4soeaje91bao53tapeq0cb7b94",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q5jdufebkjfgzn4upyqfi5sjga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
